name: Deploy Plugin

on:
  push:
    branches: [ aigent ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build plugin and generate metadata
        run: |
          ./gradlew buildPlugin updateMetadata
          echo "updateSiteUrl=https://elvedroid.github.io/deepseek-template-tc" >> gradle.properties

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/distributions
          keep_files: false
          destination_dir: .